export const APP_SET_ELEMENT_STATE = 'APP_SET_ELEMENT_STATE';
export const APP_REMOVE_ELEMENT_STATE = 'APP_REMOVE_ELEMENT_STATE';

export const APP_SET_CUSTOM_COLOR = 'APP_SET_CUSTOM_COLOR';

export const APP_LIST_APPS = 'APP_LIST_APPS';
export const APP_LIST_APPS_SUCCESS = 'APP_LIST_APPS_SUCCESS';
export const APP_LIST_APPS_FAILURE = 'APP_LIST_APPS_FAILURE';

export const APP_GET = 'APP_GET';
export const APP_GET_SUCCESS = 'APP_GET_SUCESS';
export const APP_GET_FAILURE = 'APP_GET_FAILURE';

export const APP_SAVE = 'APP_SAVE';
export const APP_SAVE_SUCCESS = 'APP_SAVE_SUCCESS';
export const APP_SAVE_FAILURE = 'APP_SAVE_FAILURE';

export const APP_ADD_DATASOURCE = 'APP_ADD_DATASOURCE';
export const APP_REMOVE_DATASOURCE = 'APP_REMOVE_DATASOURCE';
export const APP_SET_DATASOURCE = 'APP_SET_DATASOURCE';

export const APP_REMOVE = 'APP_REMOVE';
export const APP_REMOVE_SUCCESS = 'APP_REMOVE_SUCCESS';
export const APP_REMOVE_FAILURE = 'APP_REMOVE_FAILURE';