export const EDITOR_TOGGLE_EDIT_MODE = 'EDITOR/TOGGLE_EDIT_MODE';
export const EDITOR_TOGGLE_OVERLAY_MODE = 'EDITOR_TOGGLE_OVERLAY_MODE';

export const EDITOR_SET_SELECTED_TARGET = 'EDITOR_SET_SELECTED_TARGET';
export const EDITOR_SET_SELECTED_EDITOR_COMPONENT = 'EDITOR_SET_SELECTED_EDITOR_COMPONENT';