export const USER_SET_LOCALE = 'USER_SET_LOCALE';
export const USER_SET_DATE_FORMAT = ' USER_SET_DATE_FORMAT';
export const USER_FETCH_TRANSLATIONS = 'USER_FETCH_TRANSLATIONS';
export const USER_FETCH_TRANSLATIONS_SUCCESS = 'USER_FETCH_TRANSLATIONS_SUCCESS';
export const USER_FETCH_TRANSLATIONS_FAILURE = 'USER_FETCH_TRANSLATIONS_FAILURE';
export const USER_UPDATE_TRANSLATION = 'USER_UPDATE_TRANSLATION';